### ISSUE TITLE
优化输入分析逻辑，使其能够在不同分支分别读写变量时分析得到正确结果

### ISSUE THREAD

**Issue by SigureMo** [2742195759/paddle-symbolic-trace#125]
在发生子图打断的时刻，我们需要在该时刻分析之后可能用到的，且当前已存在的变量，将其作为输入传入到打断子图后抽取的函数之中

比如对于如下函数：

```python
def foo(x):
    y = x + 1
    # 如果此时分析，应该只有 y，因为 z 是后面产生的变量
    z = y + 1
    # 如果此时分析，应该只有 z
    return z
```

目前相关算法逻辑写在了

https://github.com/2742195759/paddle-symbolic-trace/blob/5df3221b692ed7282c73e864a381bb23148e6ca7/symbolic_trace/opcode_translator/instruction_utils/opcode_analysis.py#L39-L71

目前在少数情况下会出现分析错误的问题，比如对于如下代码

```python
def case6(x):
    y = x + 1
    z = x + 2

    # 如果此时分析，应该为 a 和 z，虽然本代码是可以过的，但是下面的代码是过不了的
    if z:
        a = 1
    else:
        a += 1
    return z

def case7(x):
    y = x + 1
    z = x + 2

    # 如果此时分析，这里同样应该是 a 和 z，但是分析后只有 z
    if not z:
        a += 1
    else:
        a = 1
    return z
```

本任务希望你能够修改这里输入分析时 JUMP 相关逻辑，以适配上述情况

**Comment by SigureMo** [comment]
~~需等待 #126 merge~~

任务完成后如下单测应该通过

https://github.com/2742195759/paddle-symbolic-trace/blob/ee9e0c6f6453a629c5d5df64e3681590c7254b17/tests/test_analysis_inputs.py#L125-L126

当然也欢迎添加更多单测，以确保算法的正确性～

**Comment by Difers** [comment]
这里分析逻辑有一点没看懂，“我们需要在该时刻分析之后可能用到的，**且**当前已存在的变量”，那么对case6，
```
def case6(x):
    y = x + 1
    z = x + 2

    # 如果此时分析，当前已存在的是z，a是后面产生的变量，之后可能用到的是a,z，那么结果不应该是z吗？
    if z:
        a = 1
    else:
        a += 1
```

**Comment by SigureMo** [comment]
> 这里分析逻辑有一点没看懂，“我们需要在该时刻分析之后可能用到的，且当前已存在的变量”，那么对case6，

其实这是循环的一个简化版，因为我们并不知道当前 a 是否已经存在了，对于跳转分支，应该是两个分支各自分析，之后取两个分支结果的并集

```python
def case6(x):
    y = x + 1
    z = x + 2

    for i in range(3):
        # 比如在这里分析
        if i == 0:
            a = 1
        else:
            a += 1
```

另，如果对我们的代码机制有什么问题的话，可以写在 #149，我们周四会统一解答～
