### ISSUE TITLE
部分涉及property的运算存在问题

### ISSUE THREAD

**Issue by zrr1999** [2742195759/paddle-symbolic-trace#169]
```py
def foo(cond: paddle.Tensor, x: paddle.Tensor):
    x += 1
    return x + x.size


def main():
    cond = paddle.to_tensor(True)
    x = paddle.to_tensor(0)
    dygraph_out = foo(cond, x)
    print("dygraph_out:", dygraph_out)

    symbolic_translate_out = symbolic_translate(foo)(cond, x)
    print("symbolic_translate_out:", symbolic_translate_out)
    np.testing.assert_allclose(
        dygraph_out.numpy(), symbolic_translate_out.numpy()
    )
```
期望和动态图有相同结果
<img width="937" alt="image" src="https://github.com/PaddlePaddle/PaddleSOT/assets/46243324/e2b485d7-7f65-480b-a424-241b5e50c0ff">

实际上会报错
<img width="913" alt="image" src="https://github.com/PaddlePaddle/PaddleSOT/assets/46243324/fcea1ae3-8b09-47af-868e-13773e341982">

此时如果是 x + x.size() 结果会是正确的，但是动态图会报错（因为x.size是整数）

@SigureMo @2742195759

**Comment by SigureMo** [comment]
https://github.com/PaddlePaddle/PaddleSOT/blob/d8d7c7ccd082b1577a0ecc1c667ce07e6f91c5f4/sot/opcode_translator/executor/variables/basic.py#L206-L223

```
elif name in ["T", "ndim", "size"]:
``` 

将这个分支上调即可

这是因为 paddle_tensor_methods 是从 paddle.static.Variable 自动获取的，在 Variable 上 size 是一个 method 而不是 property，故而走错分支

我之后的 PR 应该会顺手修一下这个～

**Comment by zrr1999** [comment]
> https://github.com/PaddlePaddle/PaddleSOT/blob/d8d7c7ccd082b1577a0ecc1c667ce07e6f91c5f4/sot/opcode_translator/executor/variables/basic.py#L206-L223
> 
> ```
> elif name in ["T", "ndim", "size"]:
> ```
> 
> 将这个分支上调即可
> 
> 这是因为 paddle_tensor_methods 是从 paddle.static.Variable 自动获取的，在 Variable 上 size 是一个 method 而不是 property，故而走错分支
> 
> 我之后的 PR 应该会顺手修一下这个～

好滴，明白啦
