### ISSUE TITLE
NumPy 1.25.0 更新导致 3.9、3.10 流水线失败

### ISSUE THREAD

**Issue by SigureMo** [2742195759/paddle-symbolic-trace#174]
几个小时前 NumPy 发布了 1.25.0（见 https://github.com/numpy/numpy/releases/tag/v1.25.0 ），该版本仅支持 3.9、3.10、3.11，因此不会影响我们的 3.8 流水线，而我们 Paddle 最新 Nightly 仅仅要求了 NumPy >= 1.13，不会要求上限版本，因此 CI 会自动装最新版本

https://github.com/PaddlePaddle/Paddle/blob/develop/python/requirements.txt#L2

最新版本 NumPy 有如下变动：

> ### Most NumPy functions are wrapped into a C-callable
>
> To speed up the `__array_function__` dispatching, most NumPy functions
> are now wrapped into C-callables and are not proper Python functions or
> C methods. They still look and feel the same as before (like a Python
> function), and this should only improve performance and user experience
> (cleaner tracebacks). However, please inform the NumPy developers if
> this change confuses your program for some reason.

简单来说就是将 Python API 移交到了 C 端，Python 端只是 wrapper，关于 `__array_function__` 可参见 [NEP 18](https://numpy.org/neps/nep-0018-array-function-protocol.html)

这导致我们的单测 `test_break_graph.py` 失败，因为该单测调用了 `np.sum` API，这应该通过 `from_value` 生成 `UserDefinedFunctionVariable`（因为其类型是 `FunctionType`），但是 NumPy 1.25.0 已经不是了，`np.sum` 只是一个 Dispatcher：

```python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) 
[Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.sum
<function sum at 0x1015f3a30>
>>> type(np.sum)
<class 'numpy._ArrayFunctionDispatcher'>
>>>
```

可选的解决方案：

- `requirements.txt` 里强制 numpy<1.25.0，延迟解决
- 对该类进行特判处理（具体方案需周一讨论）

**Comment by Aurelius84** [comment]
确认一下，CI 单测里直接raise NotImplementError 是因为我们设定了 strict_mode=1，未来正常情况下，这种error是会被捕获，然后fallback到动态图来执行的，对吧？

**Comment by SigureMo** [comment]
> 确认一下，CI 单测里直接raise NotImplementError 是因为我们设定了 strict_mode=1，未来正常情况下，这种error是会被捕获，然后fallback到动态图来执行的，对吧？

对，非 strict mode 现在就是 fallback 的，用户不应该开 strict mode，这只是我们开发过程中为了提前暴露问题的一个 flag（不然啥都能过单测就没啥意义了）
