### ISSUE TITLE
【提问】关于 SOT 的问题

### ISSUE THREAD

**Issue by yangguohao** [2742195759/paddle-symbolic-trace#392]
想请教一下 SOT 是如何去追踪子层的。例如 layer1 内有 sublayer1， sublayer1 里有基础的 linear、relu 算子，要如何去获取 sublayer 中的基础算子。

**Comment by gouzil** [comment]
可以把断点打在`sot/opcode_translator/executor/opcode_executor.py`的`LOAD_METHOD`上，跑`test_17_paddle_layer.py`单测，然后看看`obj`和`method`是不是你想要的

参考资料:
* #130
* #144

**Comment by yangguohao** [comment]
```
class SimpleNet(paddle.nn.Layer):
    def __init__(self):
        super().__init__()
        self.linear1 = paddle.nn.Linear(10, 1)

    def forward(self, x):
        out1 = self.linear1(x)
        return out1

class SimpleNetWithSubLayer(paddle.nn.Layer):
    def __init__(self):
        super().__init__()
        self.sublayer = paddle.nn.Sequential(SimpleNet())
        self.relu = paddle.nn.ReLU()
    def forward(self, x):
        x = self.sublayer(x)
        x = self.relu(x)
        return x
```

我想的是这样的一直情况，这样的话应该是和 bound method 相似的吗？我看了下，应该也是通过 OpcodeInlineExecutor 来实现的？

**Comment by SigureMo** [comment]
> 想请教一下 SOT 是如何去追踪子层的。

inline call，当模拟执行遇到 function call 的时候，如果它应该 inline call 的话会 inline call，这包括了：

- 用户自定义的，含 PyCodeObject 的函数
- 用户自定义 Layer
- Paddle 容器类 Layer

> 要如何去获取 sublayer 中的基础算子。

我不清楚你所说的「基础算子」是如何界定的，PaddleSOT 在编译期收集组网信息的目标不是获取基础的算子，SOT 是否能够将一个 API、Layer 放入组网信息（SIR）中的边界是它是否是动静统一的，如果它是动静统一的，就可以放到 SIR 中，因此我们可能并不会去获取你所说的「基础算子」

**Comment by yangguohao** [comment]
了解了，感谢回复了
